#include <stdlib.h>
#include <stdio.h>
#include <libgte.h>
#include <libgpu.h>
#include <libgs.h>
#include <libetc.h>
#include "sys/types.h"

// Constants
#define SCREEN_WIDTH 320
#define SCREEN_HEIGHT 240
#define NUM_BUFFERS 2
#define BUFFERS_LENGHT 1
#define MODE_NTSC 0
#define PACKETMAX 300
#define FRAME_BUFFER_WIDTH 1024
#define FRAME_BUFFER_HEIGHT 512

#define __ramsize   0x00200000 // Force 2MB vram
#define __stacksize 0x00004000

// Globals
typedef struct {
    u_short r;
    u_short g;
    u_short b;
} Color;


GsOT orderingTable[NUM_BUFFERS];
GsOT_TAG minorOrderingTable[NUM_BUFFERS][1<<BUFFERS_LENGHT];
PACKET GPUOutputPacket[NUM_BUFFERS][PACKETMAX];
u_char currentBuffer = 0;
Color backgroundColor;

DISPENV dispenv[2];
DRAWENV drawenv[2];
POLY_F3 polyf3;

// Prototypes
void initializeScreen();
void clearVRAM();
void draw();
void display();
void clearDisplay();
void initDisplayAndDrawEnvs();
void initGameObjects();

int main() {
    backgroundColor.r = 66;
    backgroundColor.g = 200;
    backgroundColor.b = 100;
    initializeScreen();
    initializeDebugFont();
    initGameObjects();

    while(1) {
        draw();
        display();
        clearDisplay();
    }

    return 0;
}

// Definitions -----------------------------------------

void initializeScreen() {
    SetVideoMode(MODE_NTSC);
    SetDispMask(1); // 1=MASK on
	ResetGraph(0);  // Initialise drawing engine, 0=Complete reset
    clearVRAM();    

    // Resets libgpu and initializes the graphic system. libpgu settings are maintaned by 
    // the global variables GsDISPENV and GsDRAWENV
    GsInitGraph(SCREEN_WIDTH, SCREEN_HEIGHT, GsINTER|GsOFSGPU, 0, 0); 
    
    // Define double buffers
    GsDefDispBuff(0, 0, 0, SCREEN_HEIGHT);

    // Initialize display and drawing environments
    SetDefDispEnv(&dispenv[0], 0, 0, SCREEN_WIDTH, SCREEN_HEIGHT);
    SetDefDrawEnv(&drawenv[0], 0, 0, SCREEN_WIDTH, SCREEN_HEIGHT);
    SetDefDispEnv(&dispenv[1], 0, 0, SCREEN_WIDTH, SCREEN_HEIGHT);
    SetDefDrawEnv(&drawenv[1], 0, 0, SCREEN_WIDTH, SCREEN_HEIGHT);

    // Initialize ordering tables
    GsClearOt(0, 0, &orderingTable[GsGetActiveBuff()]);
    orderingTable[0].length = BUFFERS_LENGHT;
    orderingTable[0].org = minorOrderingTable[0];
    orderingTable[1].length = BUFFERS_LENGHT;
    orderingTable[1].org = minorOrderingTable[1];
    GsClearOt(0, 0, &orderingTable[0]);
    GsClearOt(0, 0, &orderingTable[1]);
}

void clearVRAM() {
    RECT rect;
    setRECT(&rect, 0, 0, FRAME_BUFFER_WIDTH, FRAME_BUFFER_HEIGHT);
    ClearImage2(&rect, backgroundColor.r, backgroundColor.g, backgroundColor.b);    // Clear Frame Buffer at high speed (interlaced mode)
    DrawSync(0);    // Waits for ClearImage2 function to finish
}

void initializeDebugFont() {
	FntLoad(960, 256);
	SetDumpFnt(FntOpen(5, 20, 320, 240, 0, 512)); //Sets the dumped font for use with FntPrint();
}

void initGameObjects() {
    SetPolyF3(&polyf3);
    setXY3(&polyf3, 50, 50, 100, 100, 50, 100);
    setRGB0(&polyf3, 150, 100, 50);
}

void draw() {
    DrawPrim(&polyf3);
    FntPrint("Hello World");
}

void display() {
    currentBuffer = GsGetActiveBuff();
    PutDispEnv(&dispenv[currentBuffer]);
    PutDrawEnv(&drawenv[currentBuffer]);
    DrawSync(0);        // Wait for drawing to end
    VSync(2);           // Wait for vsync (2 = 30FPS moreless)
    GsSwapDispBuff();   // Swap buffers
    
    // Sets a screen clear command at the start of the OT. Should be called after GsSwapDispBuff.
    // Actual clearing isnt executed unti GsDrawOt() is called
    GsSortClear(backgroundColor.r, backgroundColor.g, backgroundColor.b, &orderingTable[currentBuffer]);
    // Starts execution of GPU commands registered in OT
    GsDrawOt(&orderingTable[currentBuffer]);
}

void clearDisplay() {
    currentBuffer = GsGetActiveBuff();
    FntFlush(-1);
    // Set the memory adress for storing drawing commands for drawing primitives generated by functions
    // like GsSortObject(), GsSortSprite() and GsSortBg()
    GsSetWorkBase((PACKET*)GPUOutputPacket[currentBuffer]);
    GsClearOt(0, 0, &orderingTable[currentBuffer]);
}