#include "header/gpubase.h"

GsOT orderingTable[OT_LENGTH];
GsOT_TAG minorOrderingTable[NUM_BUFFERS][20];
PACKET GPUOutputPacket[NUM_BUFFERS][10*sizeof(GsSPRITE)];

void setBounds(u_short w, u_short h) {
    screenWidth = w;
    screenHeight = h;
}

void initializeScreen(Color* bgColor) {
    int i;
    SetVideoMode(MODE_PAL);
    SetDispMask(1); // 1=MASK on
	ResetGraph(0);  // Initialise drawing engine, 0=Complete reset
    clearVRAM(bgColor);    

    // Resets libgpu and initializes the graphic system. libpgu settings are maintaned by 
    // the global variables GsDISPENV and GsDRAWENV
    GsInitGraph(screenWidth, screenHeight, GsINTER|GsOFSGPU, 0, 0); 
    
    // Define double buffers
    GsDefDispBuff(0, 0, 0, screenHeight);

    // Initialize ordering tables
    GsClearOt(0, 0, &orderingTable[GsGetActiveBuff()]);
    for(i = 0; i < NUM_BUFFERS; i++) {
        orderingTable[i].length = OT_LENGTH;
        orderingTable[i].org = minorOrderingTable[i];
        GsClearOt(0, 0, &orderingTable[i]);
    }

    PadInit(0);
}

void clearVRAM(Color* bgColor) {
    RECT rect;
    setRECT(&rect, 0, 0, FRAME_BUFFER_WIDTH, FRAME_BUFFER_HEIGHT);
    ClearImage2(&rect, bgColor->r, bgColor->g, bgColor->b);    // Clear Frame Buffer at high speed (interlaced mode)
    DrawSync(0);    // Waits for ClearImage2 function to finish
}

void initializeDebugFont(u_char bg) {
	FntLoad(960, 256);
	SetDumpFnt(FntOpen(5, 5, 320, 32, bg, 512)); //Sets the dumped font for use with FntPrint();
}

void display(Color* backgroundColor) {
    int currentBuffer = GsGetActiveBuff();
    DrawSync(0);        // Wait for drawing to end
    VSync(2);           // Wait for vsync (2 = 30FPS moreless)
    GsSwapDispBuff();   // Swap buffers
    
    // Sets a screen clear command at the start of the OT. Should be called after GsSwapDispBuff.
    // Actual clearing isnt executed unti GsDrawOt() is called
    GsSortClear(backgroundColor->r, backgroundColor->g, backgroundColor->b, &orderingTable[currentBuffer]);
    // Starts execution of GPU commands registered in OT
    GsDrawOt(&orderingTable[currentBuffer]);
}

void clearDisplay() {
    int currentBuffer = GsGetActiveBuff();
    FntFlush(-1);
    // Set the memory adress for storing drawing commands for drawing primitives generated by functions
    // like GsSortObject(), GsSortSprite() and GsSortBg()
    GsSetWorkBase((PACKET*)GPUOutputPacket[currentBuffer]);
    GsClearOt(0, 0, &orderingTable[currentBuffer]);
}

void initializeHeap() {
	printf("\nReserving 1024KB (1,048,576 Bytes) RAM... \n");
    MEM_RESERVE(HEAP_DEFALT_START_ADDR, HEAP_DEFALT_SIZE);
}

// GsGetActiveBuff() should have been called prior to calling this function
// @return pointer to ordering table at current buffer
GsOT* currentOT() {
    return &orderingTable[GsGetActiveBuff()];
}